"""'trash'

Revision ID: 0a8d21f9a092
Revises: e7ac2602439d
Create Date: 2023-03-05 16:34:28.344076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8d21f9a092'
down_revision = 'e7ac2602439d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trash',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('products_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['products_id'], ['products.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trash')
    # ### end Alembic commands ###
