"""'added_user_id'

Revision ID: 0e51f2ca71b0
Revises: 986d69bcae44
Create Date: 2023-04-16 21:05:07.894962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e51f2ca71b0'
down_revision = '986d69bcae44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order history', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'order history', 'users', ['user_id'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order history', type_='foreignkey')
    op.drop_column('order history', 'user_id')
    # ### end Alembic commands ###
