"""'initial'

Revision ID: 158103c80897
Revises: 
Create Date: 2023-03-02 13:05:55.436132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158103c80897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('desc', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('photo_url')
    )
    op.create_table('users',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
