"""'added_order_date'

Revision ID: 2c2d77765b88
Revises: 0e02a3643b32
Create Date: 2023-04-17 16:49:45.248710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2d77765b88'
down_revision = '0e02a3643b32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order history', sa.Column('order_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order history', 'order_date')
    # ### end Alembic commands ###
