"""'changed_price'

Revision ID: 518d087b54dc
Revises: 1bba51b6fc3f
Create Date: 2023-03-21 18:15:57.622915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518d087b54dc'
down_revision = '1bba51b6fc3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
