"""'added_completed_cart'

Revision ID: 52067af8493d
Revises: 2c2d77765b88
Create Date: 2023-04-17 23:52:43.589718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52067af8493d'
down_revision = '2c2d77765b88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'completed')
    # ### end Alembic commands ###
