"""'deleted_completed_cart'

Revision ID: 6be596cea80f
Revises: 52067af8493d
Create Date: 2023-04-17 23:59:05.749434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be596cea80f'
down_revision = '52067af8493d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
