"""'changed_desc'

Revision ID: 7859d8bb4d95
Revises: 518d087b54dc
Create Date: 2023-03-21 18:19:47.398323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7859d8bb4d95'
down_revision = '518d087b54dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
