"""'changed_name_trash_id_

Revision ID: 88f02e959fac
Revises: a7c25b4d9ee7
Create Date: 2023-03-25 11:16:59.183728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f02e959fac'
down_revision = 'a7c25b4d9ee7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart products', sa.Column('cart_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('cart products_trash_id_fkey', 'cart products', type_='foreignkey')
    op.create_foreign_key(None, 'cart products', 'cart', ['cart_id'], ['Id'])
    op.drop_column('cart products', 'trash_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart products', sa.Column('trash_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart products', type_='foreignkey')
    op.create_foreign_key('cart products_trash_id_fkey', 'cart products', 'cart', ['trash_id'], ['Id'])
    op.drop_column('cart products', 'cart_id')
    # ### end Alembic commands ###
