"""'order_history_added'

Revision ID: 986d69bcae44
Revises: cec3940dd78f
Create Date: 2023-04-16 20:41:00.640116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986d69bcae44'
down_revision = 'cec3940dd78f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order history',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('cart_products', sa.BigInteger(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cart_products'], ['cart products.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order history')
    # ### end Alembic commands ###
