"""'changed_cart_id'

Revision ID: a40ce3356ce4
Revises: 88f02e959fac
Create Date: 2023-03-25 11:32:30.156216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40ce3356ce4'
down_revision = '88f02e959fac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
