"""'added_cart_products_and_changed_trash_

Revision ID: a7c25b4d9ee7
Revises: b75a3822896d
Create Date: 2023-03-25 11:11:54.157572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c25b4d9ee7'
down_revision = 'b75a3822896d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('cart products',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('trash_id', sa.BigInteger(), nullable=True),
    sa.Column('products_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['products_id'], ['products.Id'], ),
    sa.ForeignKeyConstraint(['trash_id'], ['cart.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('trash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trash',
    sa.Column('Id', sa.BIGINT(), server_default=sa.text('nextval(\'"trash_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('products_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['products_id'], ['products.Id'], name='trash_products_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], name='trash_user_id_fkey'),
    sa.PrimaryKeyConstraint('Id', name='trash_pkey')
    )
    op.drop_table('cart products')
    op.drop_table('cart')
    # ### end Alembic commands ###
