"""'moved_amount_to_cart_products'

Revision ID: adf3f705e834
Revises: a40ce3356ce4
Create Date: 2023-03-25 17:17:14.952461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf3f705e834'
down_revision = 'a40ce3356ce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'amount')
    op.add_column('cart products', sa.Column('amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart products', 'amount')
    op.add_column('cart', sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
