"""'added_amount'

Revision ID: e897aac83cee
Revises: dceb66d1ab4b
Create Date: 2023-03-19 21:43:29.892185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e897aac83cee'
down_revision = 'dceb66d1ab4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trash', sa.Column('amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trash', 'amount')
    # ### end Alembic commands ###
