from aiogram.types import ReplyKeyboardMarkup

from buttons.reply import IS_ACTIVE_BUTTON, MAIN_MENU_BUTTON, SHOW_SET_BUTTON, SHOW_LAVASH_BUTTON, SHOW_SHAWARMA_BUTTON, \
    SHOW_DONAR_BUTTON, SHOW_BURGER_BUTTON, SHOW_HOT_DOG_BUTTON, SHOW_DESERTS_BUTTON, SHOW_DRINKS_BUTTON, \
    SHOW_GARNISH_BUTTON, THIRD_SET_CASE_BUTTON, FIRST_SET_CASE_BUTTON, SECOND_SET_CASE_BUTTON, FIRST_LAVASH_CASE_BUTTON, \
    SECOND_LAVASH_CASE_BUTTON, THIRD_LAVASH_CASE_BUTTON, FOURTH_LAVASH_CASE_BUTTON, FIFTH_LAVASH_CASE_BUTTON, \
    SIXTH_LAVASH_CASE_BUTTON, SEVENTH_LAVASH_CASE_BUTTON, EIGHTH_LAVASH_CASE_BUTTON, NINTH_LAVASH_CASE_BUTTON, \
    TENTH_LAVASH_CASE_BUTTON, ELEVENTH_LAVASH_CASE_BUTTON, COME_BACK_BUTTON

ADMIN_KEYBOARDS = ReplyKeyboardMarkup([
    [IS_ACTIVE_BUTTON],
    [MAIN_MENU_BUTTON]
], resize_keyboard=True)

USER_KEYBOARDS = ReplyKeyboardMarkup([
    [MAIN_MENU_BUTTON]
], resize_keyboard=True)

MENU_KEYBOARDS = ReplyKeyboardMarkup([
    [SHOW_SET_BUTTON, SHOW_LAVASH_BUTTON],
    [SHOW_SHAWARMA_BUTTON, SHOW_DONAR_BUTTON],
    [SHOW_BURGER_BUTTON, SHOW_HOT_DOG_BUTTON],
    [SHOW_DESERTS_BUTTON, SHOW_DRINKS_BUTTON],
    [SHOW_GARNISH_BUTTON],
    [COME_BACK_BUTTON]
])

SHOW_SET_KEYBOARDS = ReplyKeyboardMarkup([
    [FIRST_SET_CASE_BUTTON, SECOND_SET_CASE_BUTTON],
    [THIRD_SET_CASE_BUTTON],
    [COME_BACK_BUTTON]
], resize_keyboard=True)

SHOW_LAVASH_KEYBOARDS = ReplyKeyboardMarkup([
    [FIRST_LAVASH_CASE_BUTTON, SECOND_LAVASH_CASE_BUTTON],
    [THIRD_LAVASH_CASE_BUTTON, FOURTH_LAVASH_CASE_BUTTON],
    [FIFTH_LAVASH_CASE_BUTTON, SIXTH_LAVASH_CASE_BUTTON],
    [SEVENTH_LAVASH_CASE_BUTTON, EIGHTH_LAVASH_CASE_BUTTON],
    [NINTH_LAVASH_CASE_BUTTON, TENTH_LAVASH_CASE_BUTTON],
    [ELEVENTH_LAVASH_CASE_BUTTON],
    [COME_BACK_BUTTON]
], resize_keyboard=True)