from aiogram.types import ReplyKeyboardMarkup

from buttons.reply import IS_ACTIVE_BUTTON, MAIN_MENU_BUTTON, SHOW_SET_BUTTON, SHOW_LAVASH_BUTTON, SHOW_SHAWARMA_BUTTON, \
    SHOW_DONAR_BUTTON, SHOW_BURGER_BUTTON, SHOW_HOT_DOG_BUTTON, SHOW_DESERTS_BUTTON, SHOW_DRINKS_BUTTON, \
    SHOW_GARNISH_BUTTON, FIRST_CASE_BUTTON, SECOND_CASE_BUTTON, THIRD_CASE_BUTTON


ADMIN_KEYBOARDS = ReplyKeyboardMarkup([
    [IS_ACTIVE_BUTTON],
    [MAIN_MENU_BUTTON]
], resize_keyboard=True)

USER_KEYBOARDS = ReplyKeyboardMarkup([
    [MAIN_MENU_BUTTON]
], resize_keyboard=True)

MENU_KEYBOARDS = ReplyKeyboardMarkup([
    [SHOW_SET_BUTTON, SHOW_LAVASH_BUTTON],
    [SHOW_SHAWARMA_BUTTON, SHOW_DONAR_BUTTON],
    [SHOW_BURGER_BUTTON, SHOW_HOT_DOG_BUTTON],
    [SHOW_DESERTS_BUTTON, SHOW_DRINKS_BUTTON],
    [SHOW_GARNISH_BUTTON]
])

SHOW_SET_KEYBOARDS = ReplyKeyboardMarkup([
    [FIRST_CASE_BUTTON, SECOND_CASE_BUTTON],
    [THIRD_CASE_BUTTON]
], resize_keyboard=True)